name: CI/CD

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js for Server
        uses: actions/setup-node@v3
        with:
          node-version: 14
        # working-directory: server

      - name: Install Dependencies for Server
        run: |
          npm install
        working-directory: server

      - name: Build Server
        run: |
          npm run build
        working-directory: server

      - name: Setup Node.js for Client
        uses: actions/setup-node@v3
        with:
          node-version: 16
        # working-directory: client

      - name: Install Dependencies for Client
        run: |
          npm install
        working-directory: client

      - name: Build Client
        run: |
          npm run build
        working-directory: client

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Production
        run: |
          # Your deployment script or commands go here
        env:
          SERVER_PATH: ${{ github.workspace }}/server
          CLIENT_PATH: ${{ github.workspace }}/client
